// Proto data 
// Images from unsplash.com
// names from behindthename.com
const creators = [
  {
    id: '1',
    name: 'Sarah Mitchell',
    username: 'sarahmitchell',
    bio: 'Wedding and portrait photographer capturing authentic moments. Based in NYC, available worldwide.',
    location: 'New York, NY',
    avatar: 'https://images.unsplash.com/photo-1544124094-8aea0374da93?w=400',
    coverImage: 'https://images.unsplash.com/photo-1533091090875-1ff4acc497dd?w=1600',
    specialties: ['Wedding', 'Portrait', 'Engagement'],
    yearsExperience: 8,
    rating: 4.9,
    reviewCount: 124,
    verified: true,
    languages: ['English', 'Spanish'],
    travelAvailable: true,
    instagram: '@sarahmitchell',
    website: 'sarahmitchell.com',
  },
  {
    id: '2',
    name: 'Marcus Chen',
    username: 'marcuschen',
    bio: 'Fashion and editorial photographer with a cinematic eye. Creating bold, artistic visuals.',
    location: 'Los Angeles, CA',
    avatar: 'https://images.unsplash.com/photo-1643968612613-fd411aecd1fd?w=400',
    coverImage: 'https://images.unsplash.com/photo-1704208316515-a32f81e373ef?w=1600',
    specialties: ['Fashion', 'Editorial', 'Commercial'],
    yearsExperience: 6,
    rating: 4.8,
    reviewCount: 89,
    verified: true,
    languages: ['English', 'Mandarin'],
    travelAvailable: true,
    instagram: '@marcuschen',
  },
  {
    id: '3',
    name: 'Emma Rodriguez',
    username: 'emmarodriguez',
    bio: 'Landscape and travel photographer. Chasing light and capturing the world\'s beauty.',
    location: 'Denver, CO',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    coverImage: 'https://images.unsplash.com/photo-1544954617-f5c6b0d16164?w=1600',
    specialties: ['Landscape', 'Travel', 'Nature'],
    yearsExperience: 10,
    rating: 5.0,
    reviewCount: 156,
    verified: true,
    languages: ['English', 'French'],
    travelAvailable: true,
    instagram: '@emmarodriguez',
    website: 'emmarodriguez.photo',
  },
  {
    id: '4',
    name: 'James Park',
    username: 'jamespark',
    bio: 'Street and documentary photographer telling stories through urban landscapes.',
    location: 'Chicago, IL',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    coverImage: 'https://images.unsplash.com/photo-1628803184377-c5167a0cb6fd?w=1600',
    specialties: ['Street', 'Documentary', 'Urban'],
    yearsExperience: 5,
    rating: 4.7,
    reviewCount: 67,
    verified: false,
    languages: ['English', 'Korean'],
    travelAvailable: false,
  },
  {
    id: '5',
    name: 'Olivia Hart',
    username: 'oliviahart',
    bio: 'Food and product photographer specializing in commercial and editorial work.',
    location: 'Portland, OR',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
    coverImage: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=1600',
    specialties: ['Food', 'Product', 'Commercial'],
    yearsExperience: 7,
    rating: 4.9,
    reviewCount: 103,
    verified: true,
    languages: ['English'],
    travelAvailable: true,
  },
  {
    id: '6',
    name: 'David Kumar',
    username: 'davidkumar',
    bio: 'Wildlife and nature photographer dedicated to conservation through imagery.',
    location: 'Seattle, WA',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
    coverImage: 'https://images.unsplash.com/photo-1584282479918-1ea22427dc0f?w=1600',
    specialties: ['Wildlife', 'Nature', 'Conservation'],
    yearsExperience: 12,
    rating: 5.0,
    reviewCount: 178,
    verified: true,
    languages: ['English', 'Hindi'],
    travelAvailable: true,
    instagram: '@davidkumar',
    website: 'davidkumar.photo',
  },
];

const services = {
  '1': [
    {
      id: 's1',
      name: 'Wedding Photography',
      description: 'Full day wedding coverage with two photographers, capturing every special moment.',
      duration: '8-10 hours',
      price: 3500,
      priceType: 'starting',
      included: [
        '8-10 hours coverage',
        'Two professional photographers',
        '500+ edited high-resolution photos',
        'Online gallery',
        'Print release',
      ],
    },
    {
      id: 's2',
      name: 'Portrait Session',
      description: 'Professional portrait photography for individuals, couples, or families.',
      duration: '1-2 hours',
      price: 450,
      priceType: 'starting',
      included: [
        '1-2 hours session',
        'Multiple outfit changes',
        '30+ edited photos',
        'Online gallery',
        'Print release',
      ],
    },
    {
      id: 's3',
      name: 'Engagement Shoot',
      description: 'Romantic engagement session at location of your choice.',
      duration: '2 hours',
      price: 650,
      priceType: 'fixed',
      included: [
        '2 hours coverage',
        'Multiple locations',
        '50+ edited photos',
        'Online gallery',
        'Print release',
      ],
    },
  ],
  '2': [
    {
      id: 's4',
      name: 'Fashion Editorial',
      description: 'High-end fashion photography for magazines, lookbooks, and portfolios.',
      duration: '4-6 hours',
      price: 2500,
      priceType: 'starting',
      included: [
        '4-6 hours shoot',
        'Creative direction',
        '100+ edited photos',
        'Commercial usage rights',
      ],
    },
    {
      id: 's5',
      name: 'Brand Campaign',
      description: 'Complete brand photography package for marketing and advertising.',
      duration: 'Full day',
      price: 5000,
      priceType: 'starting',
      included: [
        'Full day shoot',
        'Creative concept development',
        '200+ edited photos',
        'Full commercial rights',
      ],
    },
  ],
};
// portfolio cards
const portfolioItems = {
  '1': [
    {
      id: 'p1',
      type: 'photo',
      url: 'https://images.unsplash.com/photo-1606800052052-a08af7148866?w=1200',
      thumbnail: 'https://images.unsplash.com/photo-1606800052052-a08af7148866?w=600',
      title: 'Garden Wedding',
      category: 'Wedding',
      likes: 234,
    },
    {
      id: 'p2',
      type: 'photo',
      url: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1200',
      thumbnail: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=600',
      title: 'First Dance',
      category: 'Wedding',
      likes: 189,
    },
    {
      id: 'p3',
      type: 'photo',
      url: 'https://images.unsplash.com/photo-1591604466107-ec97de577aff?w=1200',
      thumbnail: 'https://images.unsplash.com/photo-1591604466107-ec97de577aff?w=600',
      title: 'Golden Hour',
      category: 'Portrait',
      likes: 312,
    },
    {
      id: 'p4',
      type: 'photo',
      url: 'https://images.unsplash.com/photo-1523438885200-e635ba2c371e?w=1200',
      thumbnail: 'https://images.unsplash.com/photo-1523438885200-e635ba2c371e?w=600',
      title: 'Bride Portrait',
      category: 'Wedding',
      likes: 267,
    },
    {
      id: 'p5',
      type: 'photo',
      url: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=1200',
      thumbnail: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=600',
      title: 'Autumn Engagement',
      category: 'Engagement',
      likes: 198,
    },
    {
      id: 'p6',
      type: 'photo',
      url: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1200',
      thumbnail: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=600',
      title: 'Ceremony',
      category: 'Wedding',
      likes: 221,
    },
  ],
  '2': [
    {
      id: 'p7',
      type: 'photo',
      url: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=1200',
      thumbnail: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=600',
      title: 'Urban Fashion',
      category: 'Fashion',
      likes: 445,
    },
    {
      id: 'p8',
      type: 'photo',
      url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=1200',
      thumbnail: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600',
      title: 'Editorial',
      category: 'Fashion',
      likes: 392,
    },
    {
      id: 'p9',
      type: 'photo',
      url: 'https://images.unsplash.com/photo-1558769132-cb1aea2f3577?w=1200',
      thumbnail: 'https://images.unsplash.com/photo-1558769132-cb1aea2f3577?w=600',
      title: 'Street Style',
      category: 'Fashion',
      likes: 367,
    },
    {
      id: 'p10',
      type: 'photo',
      url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=1200',
      thumbnail: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600',
      title: 'Studio Session',
      category: 'Fashion',
      likes: 421,
    },
  ],
};
// filter specialties
const specialties = [
  'All',
  'Wedding',
  'Portrait',
  'Fashion',
  'Landscape',
  'Street',
  'Food',
  'Nature',
  'Wildlife',
  'Commercial',
];
// some misc data for the main content of the page
const features = [
  {
    icon: 'camera',
    title: 'Portfolio First',
    description: 'Showcase your work beautifully with customizable portfolios designed for visual storytelling.',
  },
  {
    icon: 'users',
    title: 'Direct Bookings',
    description: 'Connect directly with clients and manage bookings seamlessly without intermediaries.',
  },
  {
    icon: 'shield',
    title: 'Trust & Safety',
    description: 'Verified creators, secure payments, and transparent reviews build trust on both sides.',
  },
  {
    icon: 'trending-up',
    title: 'Grow Your Business',
    description: 'Get discovered by thousands of clients looking for talented photographers and videographers.',
  },
  {
    icon: 'heart',
    title: 'Community Driven',
    description: 'Join a supportive community of creators who share tips, inspiration, and opportunities.',
  },
  {
    icon: 'zap',
    title: 'Simple & Powerful',
    description: 'Easy to use tools that help you focus on what matters most - creating amazing work.',
  },
];
